import type { Metadata } from 'next'
import { Inter, Poppins } from 'next/font/google'
import './globals.css'
import Web3ModalProvider from '@/context/page'
import { cookieToInitialState } from 'wagmi'
import { config } from '@/config/page'
import {headers} from 'next/headers'

const inter = Inter({ subsets: ['latin'] })
const poppins = Poppins({ subsets: ['latin'], weight: ['400', '600', '800'  ] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const initialState = cookieToInitialState(config, headers().get("cookie"));
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-black`}>
        <Web3ModalProvider initialState={initialState}>  
          {children}
        </Web3ModalProvider>
        </body>
    </html>
  )
}
